ALTER TABLE stacks DROP COLUMN IF EXISTS notify_events;
ALTER TABLE stacks DROP COLUMN IF EXISTS slack_webhook_enc;
ALTER TABLE stacks DROP COLUMN IF EXISTS vcs_token_enc;

ALTER TABLE runs DROP COLUMN IF EXISTS plan_destroy;
ALTER TABLE runs DROP COLUMN IF EXISTS plan_change;
ALTER TABLE runs DROP COLUMN IF EXISTS plan_add;
ALTER TABLE runs DROP COLUMN IF EXISTS pr_url;
ALTER TABLE runs DROP COLUMN IF EXISTS pr_number;
