ALTER TABLE stacks
    ADD COLUMN IF NOT EXISTS is_locked   BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS lock_reason TEXT;

ALTER TABLE runs
    ADD COLUMN IF NOT EXISTS annotation TEXT;
